# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Meyer's Website
description: Hi! My name's Josh. I've spent the last decade working on speech, language, and AI. This blog is some of what I'm learning along the way. All opinions are my own.

twitter_username: _josh_meyer_
github_username: JRMeyer

# Build settings
markdown: kramdown

# syntax highlighter
highlighter: rouge

# Google services
google_analytics: UA-90329904-1


plugins:
  - jekyll-redirect-from

# Exclude files from build
exclude:
  - CLAUDE.md